import { redirect } from "next/navigation";
import PremiumShell from "@/components/PremiumShell";
import { getPrimaryRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

const nav=[{label:"Dashboard",href:"/school-admin",icon:"⌂",group:"OVERVIEW"},{label:"School Setup",href:"/school-admin/setup",icon:"⚙",group:"OVERVIEW"},{label:"User Management",href:"/school-admin/users",icon:"♙",group:"PEOPLE"},{label:"Teachers",href:"/school-admin/teachers",icon:"♟",group:"PEOPLE"},{label:"Students",href:"/school-admin/students",icon:"♚",group:"PEOPLE"},{label:"Parents & Guardians",href:"/school-admin/parents",icon:"♧",group:"PEOPLE"},{label:"Classes",href:"/school-admin/classes",icon:"▦",group:"ACADEMICS"},{label:"Subjects",href:"/school-admin/subjects",icon:"▤",group:"ACADEMICS"},{label:"Assessments",href:"/school-admin/assessments",icon:"✓",group:"ACADEMICS"},{label:"Attendance",href:"/school-admin/attendance",icon:"◷",group:"ACADEMICS"},{label:"Results & Reports",href:"/school-admin/results",icon:"▥",group:"ACADEMICS"},{label:"Analytics",href:"/school-admin/analytics",icon:"⌁",group:"ACADEMICS"}];

export default async function AttendancePage(){
 const ctx=await getPrimaryRole(); if(ctx.role!=="school_admin")redirect("/"); const s=await createClient();
 const {data:sessions}=await s.from("attendance_sessions").select("id,attendance_date,status,classes(name),terms(name),attendance_records(status)").eq("school_id",ctx.schoolId).order("attendance_date",{ascending:false}).limit(100);
 const rows=sessions||[]; const all=rows.flatMap((x:any)=>x.attendance_records||[]); const total=all.length; const present=all.filter((x:any)=>x.status==="present").length; const absent=all.filter((x:any)=>x.status==="absent").length; const late=all.filter((x:any)=>x.status==="late").length;
 return <PremiumShell schoolName={ctx.schoolName||"School Workspace"} userLabel="Administrator" roleLabel="School Admin" nav={nav}><section className="hero"><div><h1>Attendance Monitoring</h1><p>Monitor daily attendance submitted by teachers across the school.</p></div></section><section className="stats"><article className="stat"><div><small>Attendance Sessions</small><div className="value">{rows.length}</div></div></article><article className="stat"><div><small>Present</small><div className="value">{present}</div><small>{total?`${(present/total*100).toFixed(1)}% of records`:"No records"}</small></div></article><article className="stat"><div><small>Absent</small><div className="value">{absent}</div></div></article><article className="stat"><div><small>Late</small><div className="value">{late}</div></div></article></section><section className="premium-panel" style={{marginTop:18}}><div className="panelhead"><div><h2>Recent Attendance Sessions</h2><p className="note">Class-level attendance activity submitted by teaching staff.</p></div></div><div className="tablewrap"><table className="premium-table"><thead><tr><th>DATE</th><th>CLASS</th><th>TERM</th><th>PRESENT</th><th>ABSENT</th><th>LATE</th><th>STATUS</th></tr></thead><tbody>{rows.length?rows.map((x:any)=>{const rec=x.attendance_records||[];return <tr key={x.id}><td>{x.attendance_date}</td><td><b>{x.classes?.name||"—"}</b></td><td>{x.terms?.name||"—"}</td><td>{rec.filter((r:any)=>r.status==="present").length}</td><td>{rec.filter((r:any)=>r.status==="absent").length}</td><td>{rec.filter((r:any)=>r.status==="late").length}</td><td><span className="pill greenpill">{x.status}</span></td></tr>}):<tr><td colSpan={7}>No attendance sessions yet.</td></tr>}</tbody></table></div></section></PremiumShell>;
}
