"use client";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
type Option={id:string;label:string;extra?:string}; type LinkRow={id:string;guardian:string;guardian_email:string;student:string;student_number:string;relationship:string;is_primary:boolean;can_receive_notifications:boolean};
export default function GuardianLinkManager({guardians,students,links}:{guardians:Option[];students:Option[];links:LinkRow[]}){
 const router=useRouter(); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");const f=new FormData(e.currentTarget);const body={guardian_id:f.get("guardian_id"),student_id:f.get("student_id"),relationship:f.get("relationship"),is_primary:f.get("is_primary")==="on",can_receive_notifications:f.get("can_receive_notifications")==="on"};const r=await fetch("/api/school-admin/guardian-links",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();setBusy(false);if(!r.ok){setMsg(d.error||"Unable to link guardian.");return;}setMsg("Parent/guardian linked to student.");(e.currentTarget as HTMLFormElement).reset();router.refresh();}
 async function remove(row:LinkRow){if(!confirm(`Remove ${row.guardian} from ${row.student}?`))return;const r=await fetch(`/api/school-admin/guardian-links?id=${row.id}`,{method:"DELETE"});const d=await r.json();if(!r.ok){setMsg(d.error||"Unable to unlink guardian.");return;}router.refresh();}
 async function makePrimary(row:LinkRow){const r=await fetch("/api/school-admin/guardian-links",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:row.id,is_primary:true})});const d=await r.json();if(!r.ok){setMsg(d.error||"Unable to update relationship.");return;}router.refresh();}
 return <>
  <section className="premium-panel"><div className="panelhead"><div><h2>Link Parent / Guardian</h2><p className="note">Connect a guardian account to the child or children they are allowed to monitor.</p></div></div><form className="form-grid" onSubmit={submit}>
   <div className="field"><label>Parent / Guardian</label><select name="guardian_id" required><option value="">Select guardian</option>{guardians.map(x=><option key={x.id} value={x.id}>{x.label}{x.extra?` · ${x.extra}`:""}</option>)}</select></div>
   <div className="field"><label>Student</label><select name="student_id" required><option value="">Select student</option>{students.map(x=><option key={x.id} value={x.id}>{x.label}{x.extra?` · ${x.extra}`:""}</option>)}</select></div>
   <div className="field"><label>Relationship</label><select name="relationship" required defaultValue="parent"><option value="parent">Parent</option><option value="mother">Mother</option><option value="father">Father</option><option value="guardian">Guardian</option><option value="sponsor">Sponsor</option><option value="other">Other</option></select></div>
   <div className="field"><label style={{display:"flex",alignItems:"center",gap:8,marginTop:28}}><input name="is_primary" type="checkbox"/> Primary guardian</label><label style={{display:"flex",alignItems:"center",gap:8,marginTop:10}}><input name="can_receive_notifications" type="checkbox" defaultChecked/> Receive notifications</label></div>
   <div style={{gridColumn:"1/-1"}}><button className="premium-button" disabled={busy}>{busy?"Linking...":"Link Guardian"}</button></div>
  </form>{msg&&<div className="system-message" style={{marginTop:14}}>{msg}</div>}</section>
  <section className="premium-panel" style={{marginTop:18}}><div className="panelhead"><div><h2>Parent–Child Relationships</h2><p className="note">These links determine which children appear in each parent portal.</p></div><span className="count-badge">{links.length}</span></div><div className="tablewrap"><table className="premium-table"><thead><tr><th>GUARDIAN</th><th>STUDENT</th><th>RELATIONSHIP</th><th>PRIMARY</th><th>NOTIFICATIONS</th><th>ACTIONS</th></tr></thead><tbody>{links.length?links.map(x=><tr key={x.id}><td><b>{x.guardian}</b><br/><small>{x.guardian_email}</small></td><td><b>{x.student}</b><br/><small>{x.student_number}</small></td><td>{x.relationship}</td><td>{x.is_primary?<span className="pill greenpill">Primary</span>:"—"}</td><td>{x.can_receive_notifications?"Yes":"No"}</td><td><div className="admin-actions">{!x.is_primary&&<button className="mini-btn" onClick={()=>makePrimary(x)}>Make Primary</button>}<button className="mini-btn danger-btn" onClick={()=>remove(x)}>Unlink</button></div></td></tr>):<tr><td colSpan={6}>No parent-child relationships yet.</td></tr>}</tbody></table></div></section>
 </>;
}
