"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";
import NotificationBell from "@/components/NotificationBell";

type NavItem = { label: string; href: string; icon: string; group?: string };

const criticalCss=`
.premium-shell{min-height:100vh;display:grid;grid-template-columns:248px minmax(0,1fr);background:#f6f8fb;color:#172033;font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
.premium-shell *{box-sizing:border-box}.premium-shell a{text-decoration:none;color:inherit}
.premium-sidebar{background:linear-gradient(180deg,#092745,#0b3155 68%,#08233e);padding:19px 13px 15px;color:#fff;position:sticky;top:0;height:100vh;overflow:auto;display:flex;flex-direction:column}
.shell-brand{display:flex;align-items:center;gap:9px;padding:0 7px 18px}.shell-brand>span{width:36px;height:36px;border-radius:10px;background:linear-gradient(135deg,#fff,#dff7f7);color:#0d5272;display:grid;place-items:center;font-weight:900;font-size:17px}.shell-brand b{font-size:17px}.shell-brand small{display:block;color:#8eabc2;font-size:9px}
.school-chip{display:flex;align-items:center;gap:9px;padding:10px;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.07);border-radius:11px;margin-bottom:17px}.school-chip>i{font-style:normal;width:30px;height:30px;border-radius:8px;background:#12a0a6;display:grid;place-items:center;font-size:12px;font-weight:900}.school-chip small{display:block;color:#78a2ba;font-size:8px}.school-chip b{display:block;font-size:11px;margin-top:2px;max-width:155px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.nav-caption{font-size:8px;letter-spacing:.16em;color:#6588a2;padding:7px 10px}.premium-nav{display:grid;gap:2px}.premium-nav a{display:flex;align-items:center;gap:9px;color:#b9cddd;padding:8.5px 10px;border-radius:8px;font-size:12px;font-weight:600}.premium-nav a>span{width:18px;text-align:center;color:#7396ae;font-size:13px}.premium-nav a:hover{background:rgba(255,255,255,.055);color:#fff}.premium-nav a.active{background:linear-gradient(90deg,rgba(27,166,171,.2),rgba(255,255,255,.06));color:#fff;box-shadow:inset 2px 0 #24c0bf}.premium-nav a.active>span{color:#52d2d0}
.sidebar-foot{margin-top:auto;padding-top:14px;border-top:1px solid rgba(255,255,255,.08)}.sidebar-foot>a{display:flex;align-items:center;gap:8px;padding:7px}.mini-avatar,.top-avatar{border-radius:50%;display:grid;place-items:center;font-weight:800}.mini-avatar{width:30px;height:30px;background:#e5f3f5;color:#0d5972;font-size:10px}.sidebar-foot b{display:block;font-size:10px}.sidebar-foot small{font-size:8px;color:#7797ae}.sidebar-foot button{width:100%;border:0;background:transparent;color:#91aabd;font-size:10px;text-align:left;padding:8px;cursor:pointer}
.shell-content{min-width:0;background:#f6f8fb}.shell-topbar{height:58px;background:rgba(255,255,255,.96);border-bottom:1px solid #e8edf3;display:flex;align-items:center;justify-content:space-between;padding:0 24px;position:sticky;top:0;z-index:10}.breadcrumb{display:flex;align-items:center;gap:8px;font-size:10px;color:#8a97a7}.breadcrumb i{font-style:normal;color:#c3ccd5}.breadcrumb b{color:#31455d}.shell-tools{display:flex;align-items:center;gap:9px}.status-chip{border:1px solid #e5ebf0;border-radius:999px;padding:6px 9px;font-size:9px;color:#6f7e8f;background:#fff}.status-chip i{display:inline-block;width:6px;height:6px;border-radius:50%;background:#25a76f;margin-right:5px}.top-avatar{width:31px;height:31px;background:linear-gradient(135deg,#dcebf4,#d9f2ef);color:#13526e;font-size:10px;border:1px solid #d5e3eb}
.compact-main{padding:23px 26px 36px;max-width:1480px;margin:auto}.mobilebar{display:none}.overlay{display:none}
@media(max-width:780px){.premium-shell{display:block}.premium-sidebar{position:fixed;left:-260px;width:248px;z-index:30;transition:.22s}.premium-sidebar.open{left:0}.overlay.show{display:block;position:fixed;inset:0;background:rgba(4,15,29,.42);z-index:20}.shell-topbar{display:none}.mobilebar{display:flex;background:#fff;border-bottom:1px solid #e7edf3;padding:10px 14px;position:sticky;top:0;z-index:10;align-items:center;justify-content:space-between}.compact-main{padding:16px}}
`;

export default function PremiumShell({schoolName,schoolLocation="Freetown, Sierra Leone",userLabel,roleLabel,nav,children}:{schoolName:string;schoolLocation?:string;userLabel:string;roleLabel:string;nav:NavItem[];children:React.ReactNode}) {
  const [open,setOpen]=useState(false);
  const pathname=usePathname();
  let effectiveNav=[...nav];
  if(roleLabel.toLowerCase().includes("school admin")){
    if(!effectiveNav.some(item=>item.href==="/school-admin/calendar-timetable")) effectiveNav.push({label:"Calendar & Timetable",href:"/school-admin/calendar-timetable",icon:"◫",group:"ACADEMICS"});
    if(!effectiveNav.some(item=>item.href==="/school-admin/announcements")) effectiveNav.push({label:"Announcements",href:"/school-admin/announcements",icon:"✉",group:"COMMUNICATION"});
    if(!effectiveNav.some(item=>item.href==="/school-admin/support")) effectiveNav.push({label:"Help & Support",href:"/school-admin/support",icon:"?",group:"SUPPORT"});
  }
  async function logout(){const supabase=createClient();try{await fetch("/api/security-events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"logout"})})}catch{}await supabase.auth.signOut();location.href="/login"}
  let lastGroup="";
  return <><style dangerouslySetInnerHTML={{__html:criticalCss}}/><div className={`overlay ${open?"show":""}`} onClick={()=>setOpen(false)}/><div className="shell premium-shell"><aside className={`premium-sidebar ${open?"open":""}`}><Link href="/school-admin" className="shell-brand"><span>E</span><div><b>E-School</b><small>Digital Campus</small></div></Link><div className="school-chip"><i>{schoolName.slice(0,1).toUpperCase()}</i><div><small>SCHOOL WORKSPACE</small><b>{schoolName}</b><small>{schoolLocation}</small></div></div><div className="nav-caption">NAVIGATION</div><nav className="premium-nav">{effectiveNav.map(item=>{const group=item.group||"";const groupNode=group&&group!==lastGroup?<div className="nav-caption" key={`${group}-label`}>{group}</div>:null;lastGroup=group;const active=pathname===item.href;return <div key={item.href}>{groupNode}<Link href={item.href} className={active?"active":""} onClick={()=>setOpen(false)}><span>{item.icon}</span>{item.label}</Link></div>})}</nav><div className="sidebar-foot"><Link href="/account"><span className="mini-avatar">{roleLabel.slice(0,1).toUpperCase()}</span><div><b>{userLabel}</b><small>{roleLabel}</small></div></Link><button onClick={logout}>Sign out ↗</button></div></aside><section className="content shell-content"><header className="mobilebar"><button className="menu" onClick={()=>setOpen(true)}>☰</button><strong>E-School</strong><NotificationBell roleLabel={roleLabel}/></header><header className="shell-topbar"><div className="breadcrumb"><span>E-School</span><i>/</i><b>{schoolName}</b></div><div className="shell-tools"><div className="status-chip"><i></i> School workspace</div><NotificationBell roleLabel={roleLabel}/><Link href="/account" className="top-avatar">{roleLabel.slice(0,1).toUpperCase()}</Link></div></header><main className="main compact-main">{children}</main></section></div></>;
}
