"use client";
import {FormEvent,useState} from "react";
import {useRouter} from "next/navigation";

type Props={school:any;years:any[];terms:any[];levels:any[]};
export default function SchoolSetupManager({school,years,terms,levels}:Props){
 const router=useRouter();const[busy,setBusy]=useState("");const[msg,setMsg]=useState("");
 async function send(action:string,payload:any){setBusy(action);setMsg("");const r=await fetch("/api/school-admin/setup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});const d=await r.json();setBusy("");if(!r.ok){setMsg(d.error||"Action failed.");return false;}setMsg("Changes saved successfully.");router.refresh();return true;}
 async function submit(e:FormEvent<HTMLFormElement>,action:string){e.preventDefault();const f=new FormData(e.currentTarget);const payload=Object.fromEntries(f.entries());if(action==="create_year")payload.is_current=f.get("is_current")==="on";const ok=await send(action,payload);if(ok&&action!=="update_school")(e.currentTarget as HTMLFormElement).reset();}
 return <>
  {msg&&<div className="system-message" style={{marginBottom:16}}>{msg}</div>}
  <section className="premium-grid">
   <article className="premium-panel"><div className="panelhead"><div><h2>School Profile</h2><small>Keep official school contact information current.</small></div></div><form className="form-grid" onSubmit={e=>submit(e,"update_school")}>
    <div className="field"><label>School Name</label><input value={school.name} disabled/></div><div className="field"><label>School Code</label><input value={school.school_code} disabled/></div><div className="field"><label>Email</label><input name="email" type="email" defaultValue={school.email||""}/></div><div className="field"><label>Phone</label><input name="phone" defaultValue={school.phone||""}/></div><div className="field"><label>City</label><input name="city" defaultValue={school.city||""}/></div><div className="field"><label>Country</label><input name="country" defaultValue={school.country||"Sierra Leone"}/></div><div className="field" style={{gridColumn:"1/-1"}}><label>Address</label><input name="address" defaultValue={school.address||""}/></div><div style={{gridColumn:"1/-1"}}><button className="premium-button" disabled={busy==="update_school"}>{busy==="update_school"?"Saving...":"Save School Profile"}</button></div>
   </form></article>
   <article className="premium-panel"><div className="panelhead"><div><h2>Setup Progress</h2><small>Complete these before onboarding students.</small></div></div>
    {[['Academic year',years.length>0],['Terms',terms.length>0],['Class levels',levels.length>0]].map(([label,done]:any)=><div className="action" key={label}><div className="aico">{done?'✓':'○'}</div><div><strong>{label}</strong><small>{done?'Configured':'Not configured yet'}</small></div></div>)}
   </article>
  </section>
  <section className="premium-grid">
   <article className="premium-panel"><div className="panelhead"><div><h2>Academic Years</h2><small>Create and identify the current school year.</small></div></div><form className="form-grid" onSubmit={e=>submit(e,"create_year")}><div className="field"><label>Name</label><input name="name" required placeholder="2026/2027"/></div><div className="field"><label>Status</label><select name="status"><option value="upcoming">Upcoming</option><option value="active">Active</option><option value="completed">Completed</option></select></div><div className="field"><label>Start date</label><input name="start_date" type="date" required/></div><div className="field"><label>End date</label><input name="end_date" type="date" required/></div><label className="note" style={{gridColumn:"1/-1"}}><input name="is_current" type="checkbox"/> Set as current academic year</label><div style={{gridColumn:"1/-1"}}><button className="premium-button" disabled={busy==="create_year"}>Add Academic Year</button></div></form>
    <div className="list" style={{marginTop:14}}>{years.map(y=><div className="row" key={y.id}><div><b>{y.name}</b><small style={{display:'block'}}>{y.start_date} → {y.end_date}</small></div><span className={`pill ${y.is_current?'greenpill':'amberpill'}`}>{y.is_current?'Current':y.status}</span></div>)}</div>
   </article>
   <article className="premium-panel"><div className="panelhead"><div><h2>Terms / Semesters</h2><small>Define reporting periods under an academic year.</small></div></div><form className="form-grid" onSubmit={e=>submit(e,"create_term")}><div className="field" style={{gridColumn:"1/-1"}}><label>Academic Year</label><select name="academic_year_id" required><option value="">Select year</option>{years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></div><div className="field"><label>Term name</label><input name="name" required placeholder="Term 1"/></div><div className="field"><label>Sequence</label><input name="sequence_number" type="number" min="1" defaultValue="1"/></div><div className="field"><label>Start date</label><input name="start_date" type="date" required/></div><div className="field"><label>End date</label><input name="end_date" type="date" required/></div><div style={{gridColumn:"1/-1"}}><button className="premium-button" disabled={busy==="create_term"}>Add Term</button></div></form>
    <div className="list" style={{marginTop:14}}>{terms.map(t=><div className="row" key={t.id}><div><b>{t.name}</b><small style={{display:'block'}}>{t.academic_years?.name||''}</small></div><span className="pill amberpill">{t.status}</span></div>)}</div>
   </article>
  </section>
  <section className="premium-panel" style={{marginTop:18}}><div className="panelhead"><div><h2>Class Levels</h2><small>Create the school's hierarchy before opening actual classes.</small></div></div><form className="form-grid" onSubmit={e=>submit(e,"create_level")}><div className="field"><label>Level name</label><input name="name" required placeholder="JSS 1"/></div><div className="field"><label>Code</label><input name="code" placeholder="JSS1"/></div><div className="field"><label>Sequence</label><input name="sequence_number" type="number" min="1" defaultValue="1"/></div><div className="field" style={{display:'flex',alignItems:'end'}}><button className="premium-button" disabled={busy==="create_level"}>Add Class Level</button></div></form><div className="quickgrid">{levels.map(l=><article className="quick" key={l.id}><div>▦</div><b>{l.name}</b><small>{l.code||'No code'} · Level {l.sequence_number||'—'}</small></article>)}</div></section>
 </>;
}
