"use client";
import {FormEvent,useState} from "react";
import {useRouter} from "next/navigation";

type UserRow={user_id:string;role:string;is_active:boolean;first_name:string;last_name:string;email:string;phone:string|null};
export default function SchoolUserManager({users}:{users:UserRow[]}){
 const router=useRouter();const[role,setRole]=useState("");const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");const f=new FormData(e.currentTarget);const password=String(f.get("password")||"");const confirm=String(f.get("confirm_password")||"");if(password!==confirm){setBusy(false);setMsg("Temporary passwords do not match.");return;}const payload=Object.fromEntries(f.entries());delete (payload as any).confirm_password;const r=await fetch("/api/admin/users/invite",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();setBusy(false);if(!r.ok){setMsg(d.error||"Unable to create account.");return;}setMsg(`${roleLabel(role)} account created successfully. The user must change the temporary password at first login.`);(e.currentTarget as HTMLFormElement).reset();setRole("");router.refresh();}
 const roleLabel=(r:string)=>r==="parent"?"Parent / Guardian":r.charAt(0).toUpperCase()+r.slice(1);
 return <>
  <section className="premium-grid">
   <article className="premium-panel"><div className="panelhead"><div><h2>Create School User</h2><small>Create a secure account directly under this school.</small></div></div><form onSubmit={submit} className="form-grid">
    <div className="field"><label>First name</label><input name="first_name" required/></div><div className="field"><label>Last name</label><input name="last_name" required/></div><div className="field"><label>Email</label><input name="email" type="email" required/></div><div className="field"><label>Phone</label><input name="phone"/></div>
    <div className="field"><label>Role</label><select name="role" value={role} onChange={e=>setRole(e.target.value)} required><option value="">Select role</option><option value="teacher">Teacher</option><option value="parent">Parent / Guardian</option><option value="student">Student</option></select></div><div className="field"><label>Temporary password</label><input name="password" type="password" minLength={8} required/></div><div className="field"><label>Confirm temporary password</label><input name="confirm_password" type="password" minLength={8} required/></div>
    {role==="teacher"&&<><div className="field"><label>Teacher number</label><input name="teacher_number" required placeholder="TCH-001"/></div><div className="field"><label>Specialization</label><input name="specialization" placeholder="Mathematics"/></div><div className="field"><label>Hire date</label><input name="hire_date" type="date"/></div></>}
    {role==="parent"&&<><div className="field"><label>Occupation</label><input name="occupation"/></div><div className="field"><label>Address</label><input name="address"/></div></>}
    {role==="student"&&<><div className="field"><label>Student number</label><input name="student_number" required placeholder="STD-0001"/></div><div className="field"><label>Admission number</label><input name="admission_number"/></div><div className="field"><label>Middle name</label><input name="middle_name"/></div><div className="field"><label>Date of birth</label><input name="date_of_birth" type="date"/></div><div className="field"><label>Gender</label><select name="gender"><option value="">Select</option><option value="male">Male</option><option value="female">Female</option><option value="other">Other</option></select></div><div className="field"><label>Admission date</label><input name="admission_date" type="date"/></div></>}
    <div style={{gridColumn:"1/-1"}}><button className="premium-button" disabled={busy}>{busy?"Creating account...":"Create User Account"}</button></div>
   </form>{msg&&<div className="system-message" style={{marginTop:14}}>{msg}</div>}</article>
   <article className="premium-panel"><div className="panelhead"><div><h2>Access Rules</h2><small>How account ownership works.</small></div></div><div className="action"><div className="aico">✓</div><div><strong>School-scoped</strong><small>Every account is tied to this school in the backend.</small></div></div><div className="action"><div className="aico">✓</div><div><strong>First-login password change</strong><small>Temporary passwords cannot remain permanent.</small></div></div><div className="action"><div className="aico">✓</div><div><strong>Role-controlled routing</strong><small>Users never choose their role on the login screen.</small></div></div></article>
  </section>
  <section className="premium-panel" style={{marginTop:18}}><div className="panelhead"><div><h2>School Users</h2><small>Current accounts assigned to this school.</small></div><span className="count-badge">{users.length}</span></div><div className="tablewrap"><table className="premium-table"><thead><tr><th>NAME</th><th>EMAIL</th><th>ROLE</th><th>STATUS</th></tr></thead><tbody>{users.length?users.map(u=><tr key={`${u.user_id}-${u.role}`}><td><b>{u.first_name} {u.last_name}</b><br/><small>{u.phone||""}</small></td><td>{u.email}</td><td>{roleLabel(u.role)}</td><td><span className={`pill ${u.is_active?"greenpill":"amberpill"}`}>{u.is_active?"Active":"Inactive"}</span></td></tr>):<tr><td colSpan={4}>No school users have been created yet.</td></tr>}</tbody></table></div></section>
 </>;
}
