"use client";
import {useMemo,useState} from "react";
type Props={schools:any[];users:any[];students:any[];teachers:any[];classes:any[];assessments:any[];attendance:any[];subscriptions:any[];payments:any[];scores:any[];reportCards:any[];subjects:any[];terms:any[];years:any[]};
export default function SuperAdminAnalytics(p:Props){
 const[school,setSchool]=useState("all"),[year,setYear]=useState("all"),[term,setTerm]=useState("all");
 const scoped=(rows:any[])=>rows.filter(x=>(school==="all"||x.school_id===school)&&(year==="all"||!x.academic_year_id||x.academic_year_id===year)&&(term==="all"||!x.term_id||x.term_id===term));
 const students=scoped(p.students),teachers=scoped(p.teachers),classes=scoped(p.classes),assessments=scoped(p.assessments),attendance=scoped(p.attendance),subs=scoped(p.subscriptions),payments=scoped(p.payments),scores=scoped(p.scores),cards=scoped(p.reportCards);
 const avg=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;const validScores=scores.map(x=>Number(x.percentage_score)).filter(Number.isFinite);const avgScore=avg(validScores);const passRate=validScores.length?validScores.filter(x=>x>=50).length/validScores.length*100:0;const atRisk=cards.filter(x=>Number(x.overall_percentage)<50||Number(x.attendance_percentage)<75).length;
 const attendanceRate=attendance.length?attendance.filter(x=>x.status==="present").length/attendance.length*100:0;const published=assessments.filter(x=>x.status==="published").length;
 const subjectRows=useMemo(()=>p.subjects.map(s=>{const xs=scores.filter(x=>x.subject_id===s.id).map(x=>Number(x.percentage_score)).filter(Number.isFinite);return{id:s.id,name:s.name,school_id:s.school_id,count:xs.length,average:avg(xs),pass:xs.length?xs.filter(x=>x>=50).length/xs.length*100:0}}).filter(x=>(school==="all"||x.school_id===school)&&x.count).sort((a,b)=>b.average-a.average),[p.subjects,scores,school]);
 const classRows=useMemo(()=>classes.map(c=>{const xs=cards.filter(x=>x.class_id===c.id).map(x=>Number(x.overall_percentage)).filter(Number.isFinite);return{id:c.id,name:c.name,count:xs.length,average:avg(xs),atRisk:cards.filter(x=>x.class_id===c.id&&(Number(x.overall_percentage)<50||Number(x.attendance_percentage)<75)).length}}).filter(x=>x.count).sort((a,b)=>b.average-a.average),[classes,cards]);
 const riskRows=cards.filter(x=>Number(x.overall_percentage)<50||Number(x.attendance_percentage)<75).sort((a,b)=>Number(a.overall_percentage)-Number(b.overall_percentage)).slice(0,20);
 return <><section className="premium-panel"><div className="panelhead"><div><h2>Academic & Platform Intelligence</h2><p className="note">Live education intelligence calculated from recorded E-School data. No estimated values are used.</p></div></div><div className="form-grid"><label className="field"><span>School</span><select value={school} onChange={e=>setSchool(e.target.value)}><option value="all">All schools</option>{p.schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field"><span>Academic Year</span><select value={year} onChange={e=>setYear(e.target.value)}><option value="all">All years</option>{p.years.filter(x=>school==="all"||x.school_id===school).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="field"><span>Term</span><select value={term} onChange={e=>setTerm(e.target.value)}><option value="all">All terms</option>{p.terms.filter(x=>(school==="all"||x.school_id===school)&&(year==="all"||x.academic_year_id===year)).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div></section>
 <section className="stats" style={{marginTop:18}}><article className="stat"><div><small>Students</small><div className="value">{students.length}</div></div></article><article className="stat"><div><small>Average Score</small><div className="value">{validScores.length?`${avgScore.toFixed(1)}%`:"—"}</div></div></article><article className="stat"><div><small>Pass Rate</small><div className="value">{validScores.length?`${passRate.toFixed(1)}%`:"—"}</div></div></article><article className="stat"><div><small>Attendance Rate</small><div className="value">{attendance.length?`${attendanceRate.toFixed(1)}%`:"—"}</div></div></article><article className="stat"><div><small>At-Risk Reports</small><div className="value">{cards.length?atRisk:"—"}</div><small>Below 50% or 75% attendance</small></div></article><article className="stat"><div><small>Published Assessments</small><div className="value">{published}</div><small>{assessments.length} total</small></div></article></section>
 <div className="premium-grid" style={{marginTop:18}}><section className="premium-panel"><div className="panelhead"><div><h2>Subject Performance</h2><p className="note">Average recorded assessment performance by subject.</p></div></div>{subjectRows.length?subjectRows.slice(0,12).map(x=><div key={x.id} style={{marginBottom:14}}><div style={{display:"flex",justifyContent:"space-between"}}><b>{x.name}</b><span>{x.average.toFixed(1)}% · {x.pass.toFixed(0)}% pass</span></div><div style={{height:9,background:"#edf2f7",borderRadius:20,overflow:"hidden",marginTop:6}}><div style={{height:"100%",width:`${Math.min(100,x.average)}%`,background:"currentColor"}}/></div></div>):<div className="empty">Subject performance will appear when scores are recorded.</div>}</section><section className="premium-panel"><div className="panelhead"><div><h2>Class Comparison</h2><p className="note">Overall report-card averages and intervention counts.</p></div></div><div className="tablewrap"><table className="premium-table"><thead><tr><th>CLASS</th><th>REPORTS</th><th>AVERAGE</th><th>AT RISK</th></tr></thead><tbody>{classRows.length?classRows.map(x=><tr key={x.id}><td><b>{x.name}</b></td><td>{x.count}</td><td>{x.average.toFixed(1)}%</td><td>{x.atRisk}</td></tr>):<tr><td colSpan={4}>No generated class results yet.</td></tr>}</tbody></table></div></section></div>
 <section className="premium-panel" style={{marginTop:18}}><div className="panelhead"><div><h2>Student Intervention Watchlist</h2><p className="note">Students whose generated report indicates academic performance below 50% or attendance below 75%. This is an intervention flag, not a diagnosis.</p></div></div><div className="tablewrap"><table className="premium-table"><thead><tr><th>STUDENT</th><th>SCHOOL</th><th>CLASS</th><th>ACADEMIC</th><th>ATTENDANCE</th><th>STATUS</th></tr></thead><tbody>{riskRows.length?riskRows.map(x=><tr key={x.id}><td><b>{x.student_name||"Student"}</b><br/><small>{x.student_number||""}</small></td><td>{x.school_name||"—"}</td><td>{x.class_name||"—"}</td><td>{x.overall_percentage==null?"—":`${Number(x.overall_percentage).toFixed(1)}%`}</td><td>{x.attendance_percentage==null?"—":`${Number(x.attendance_percentage).toFixed(1)}%`}</td><td><span className="pill amberpill">Needs attention</span></td></tr>):<tr><td colSpan={6}>No students currently meet the intervention thresholds in the selected data.</td></tr>}</tbody></table></div></section></>;
}
