"use client";
import { useMemo,useState } from "react";
import { useRouter } from "next/navigation";

export default function SuperAdminPlatformUsers({users}:{users:any[]}){
 const r=useRouter(); const[busy,setBusy]=useState(""); const[q,setQ]=useState(""); const[role,setRole]=useState("all"); const[school,setSchool]=useState("all");
 const schools=useMemo(()=>Array.from(new Map(users.filter(u=>u.school_id).map(u=>[u.school_id,u.school_name])).entries()),[users]);
 const filtered=users.filter(u=>{const text=`${u.first_name||""} ${u.last_name||""} ${u.email||""} ${u.school_name||""}`.toLowerCase();return text.includes(q.toLowerCase())&&(role==="all"||u.role===role)&&(school==="all"||u.school_id===school)});
 async function act(userId:string,action:string,extra:any={}){setBusy(userId+action);const res=await fetch("/api/admin/platform-users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({user_id:userId,action,...extra})});const d=await res.json();setBusy("");if(!res.ok)return alert(d.error||"Action failed");if(d.temporary_password)alert(`Temporary password: ${d.temporary_password}\nThe user must change it after login.`);r.refresh()}
 const active=users.filter(u=>u.profile_active&&u.role_active).length;
 return <><section className="stats"><article className="stat"><div><small>Total Platform Users</small><div className="value">{users.length}</div></div></article><article className="stat"><div><small>Active Users</small><div className="value">{active}</div></div></article><article className="stat"><div><small>School Admins</small><div className="value">{users.filter(u=>u.role==="school_admin").length}</div></div></article><article className="stat"><div><small>Teachers</small><div className="value">{users.filter(u=>u.role==="teacher").length}</div></div></article><article className="stat"><div><small>Students</small><div className="value">{users.filter(u=>u.role==="student").length}</div></div></article><article className="stat"><div><small>Parents</small><div className="value">{users.filter(u=>u.role==="parent").length}</div></div></article></section>
 <section className="premium-panel" style={{marginTop:18}}><div className="panelhead"><div><h2>Platform User Directory</h2><p className="note">Central account administration across every school on E-School.</p></div></div><div className="form-grid"><label className="field"><span>Search</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Name, email or school"/></label><label className="field"><span>Role</span><select value={role} onChange={e=>setRole(e.target.value)}><option value="all">All roles</option><option value="super_admin">Super Admin</option><option value="school_admin">School Admin</option><option value="teacher">Teacher</option><option value="student">Student</option><option value="parent">Parent</option></select></label><label className="field"><span>School</span><select value={school} onChange={e=>setSchool(e.target.value)}><option value="all">All schools</option>{schools.map(([id,name]:any)=><option key={id} value={id}>{name}</option>)}</select></label></div><div className="tablewrap" style={{marginTop:16}}><table className="premium-table"><thead><tr><th>USER</th><th>ROLE</th><th>SCHOOL</th><th>STATUS</th><th>JOINED</th><th>ACCOUNT ACTIONS</th></tr></thead><tbody>{filtered.length?filtered.map(u=><tr key={`${u.user_id}-${u.role_id}`}><td><b>{u.first_name||""} {u.last_name||""}</b><br/><small>{u.email||"No email"}</small>{u.phone?<><br/><small>{u.phone}</small></>:null}</td><td>{String(u.role).replace("_"," ")}</td><td>{u.school_name||"Platform"}<br/><small>{u.school_code||""}</small></td><td><span className={`pill ${u.profile_active&&u.role_active?"greenpill":"amberpill"}`}>{u.profile_active&&u.role_active?"Active":"Disabled"}</span></td><td>{u.created_at?new Date(u.created_at).toLocaleDateString():"—"}</td><td><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button className="mini-btn" disabled={!!busy||u.role==="super_admin"} onClick={()=>act(u.user_id,u.profile_active&&u.role_active?"disable":"enable")}>{u.profile_active&&u.role_active?"Disable":"Enable"}</button><button className="mini-btn" disabled={!!busy} onClick={()=>{const p=prompt("Enter a temporary password (minimum 8 characters). The user will be required to change it after login.");if(p)act(u.user_id,"reset_password",{password:p})}}>Reset Password</button></div></td></tr>):<tr><td colSpan={6}>No users match these filters.</td></tr>}</tbody></table></div></section></>;
}
