"use client";
import {useMemo,useState} from "react";

function label(v:string){return String(v||"—").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}
export default function SuperAdminAuditLogs({logs}:{logs:any[]}){
 const[q,setQ]=useState("");const[action,setAction]=useState("all");const[school,setSchool]=useState("all");const[expanded,setExpanded]=useState("");
 const actions=useMemo(()=>[...new Set(logs.map(x=>x.action).filter(Boolean))].sort(),[logs]);
 const schools=useMemo(()=>Array.from(new Map(logs.filter(x=>x.school_id).map(x=>[x.school_id,x.school_name||"Unknown School"])).entries()),[logs]);
 const filtered=logs.filter(x=>{const text=`${x.actor_name||""} ${x.actor_email||""} ${x.action||""} ${x.entity_type||""} ${x.school_name||""} ${x.reason||""}`.toLowerCase();return text.includes(q.toLowerCase())&&(action==="all"||x.action===action)&&(school==="all"||x.school_id===school)});
 const today=new Date().toDateString();const todayCount=logs.filter(x=>new Date(x.created_at).toDateString()===today).length;const userActions=logs.filter(x=>String(x.entity_type||"").includes("user")||String(x.action||"").includes("user")).length;const schoolActions=logs.filter(x=>x.school_id).length;
 return <><section className="stats"><article className="stat"><div><small>Recorded Events</small><div className="value">{logs.length}</div></div></article><article className="stat"><div><small>Today</small><div className="value">{todayCount}</div></div></article><article className="stat"><div><small>User & Access Events</small><div className="value">{userActions}</div></div></article><article className="stat"><div><small>School-linked Events</small><div className="value">{schoolActions}</div></div></article></section><section className="premium-panel" style={{marginTop:18}}><div className="panelhead"><div><h2>Audit Trail</h2><p className="note">Chronological record of important administrative and academic actions across the platform.</p></div></div><div className="form-grid"><label className="field"><span>Search Activity</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="User, action, school or record"/></label><label className="field"><span>Action</span><select value={action} onChange={e=>setAction(e.target.value)}><option value="all">All actions</option>{actions.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><label className="field"><span>School</span><select value={school} onChange={e=>setSchool(e.target.value)}><option value="all">All schools</option>{schools.map(([id,name]:any)=><option key={id} value={id}>{name}</option>)}</select></label></div><div className="tablewrap" style={{marginTop:16}}><table className="premium-table"><thead><tr><th>DATE & TIME</th><th>ACTOR</th><th>ACTION</th><th>SCHOOL</th><th>RECORD</th><th>DETAILS</th></tr></thead><tbody>{filtered.length?filtered.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString()}</td><td><b>{x.actor_name||"System"}</b><br/><small>{x.actor_email||"Automated/System action"}</small></td><td><span className="pill greenpill">{label(x.action)}</span></td><td>{x.school_name||"Platform"}<br/><small>{x.school_code||""}</small></td><td>{label(x.entity_type)}{x.entity_id?<><br/><small>{String(x.entity_id).slice(0,8)}…</small></>:null}</td><td><button className="mini-btn" onClick={()=>setExpanded(expanded===x.id?"":x.id)}>{expanded===x.id?"Hide":"View"}</button>{expanded===x.id?<div style={{marginTop:8,maxWidth:360,fontSize:12,lineHeight:1.5}}>{x.reason?<div><b>Reason:</b> {x.reason}</div>:null}{x.old_values?<div><b>Previous:</b> <code>{JSON.stringify(x.old_values)}</code></div>:null}{x.new_values?<div><b>New:</b> <code>{JSON.stringify(x.new_values)}</code></div>:null}{!x.reason&&!x.old_values&&!x.new_values?<span>No additional details recorded.</span>:null}</div>:null}</td></tr>):<tr><td colSpan={6}>No audit events match these filters.</td></tr>}</tbody></table></div></section></>;
}
