"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export default function TeacherRemarksWorkspace({ assignments, terms, students, remarks }: { assignments:any[]; terms:any[]; students:any[]; remarks:any[] }) {
  const router=useRouter(); const [assignmentId,setAssignmentId]=useState(assignments[0]?.id||""); const [busy,setBusy]=useState(false);
  const assignment=assignments.find((a)=>a.id===assignmentId); const roster=assignment?students.filter((s)=>s.class_id===assignment.class_id&&s.academic_year_id===assignment.academic_year_id):[];
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const response=await fetch("/api/teacher/remarks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...Object.fromEntries(f.entries()),assignment_id:assignmentId})});const data=await response.json();setBusy(false);if(!response.ok)return alert(data.error||"Unable to save remark.");(e.currentTarget as HTMLFormElement).reset();alert("Student feedback saved.");router.refresh();}
  return <><section className="premium-panel"><div className="panelhead"><div><h2>Student Development Feedback</h2><p className="note">Record academic, behavioural, participation or general development observations.</p></div></div><form className="form-grid" onSubmit={submit}><label className="field"><span>Teaching Assignment</span><select value={assignmentId} onChange={(e)=>setAssignmentId(e.target.value)}>{assignments.map((a)=><option key={a.id} value={a.id}>{a.classes?.name} · {a.subjects?.name}</option>)}</select></label><label className="field"><span>Student</span><select name="student_id" required><option value="">Select student</option>{roster.map((s)=><option key={s.student_id} value={s.student_id}>{s.students?.first_name} {s.students?.last_name}</option>)}</select></label><label className="field"><span>Term</span><select name="term_id" required><option value="">Select term</option>{terms.filter((t)=>!assignment||t.academic_year_id===assignment.academic_year_id).map((t)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="field"><span>Feedback Type</span><select name="remark_type"><option value="development">Development</option><option value="academic">Academic</option><option value="behaviour">Behaviour</option><option value="participation">Participation</option><option value="commendation">Commendation</option><option value="concern">Concern</option></select></label><label className="field"><span>Visibility</span><select name="visibility"><option value="parent_student">Parent & Student</option><option value="school_only">School Only</option></select></label><label className="field" style={{gridColumn:"1 / -1"}}><span>Remark / Observation</span><textarea name="remark" required rows={4} placeholder="Write a clear, constructive observation about this student's development..." /></label><button className="premium-button" disabled={busy}>{busy?"Saving...":"Save Feedback"}</button></form></section><section className="premium-panel" style={{marginTop:18}}><div className="panelhead"><div><h2>Recent Feedback</h2></div></div><div className="tablewrap"><table className="premium-table"><thead><tr><th>STUDENT</th><th>TYPE</th><th>REMARK</th><th>VISIBILITY</th></tr></thead><tbody>{remarks.length?remarks.map((x)=><tr key={x.id}><td><b>{x.students?.first_name} {x.students?.last_name}</b></td><td>{x.remark_type}</td><td>{x.remark}</td><td>{x.visibility==="school_only"?"School only":"Parent & Student"}</td></tr>):<tr><td colSpan={4}>No feedback recorded yet.</td></tr>}</tbody></table></div></section></>;
}
