import {NextResponse} from "next/server";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";

async function context(){const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)return null;const{data:r}=await s.from("user_school_roles").select("role,school_id").eq("user_id",user.id).eq("is_active",true).eq("role","school_admin").maybeSingle();return r?.school_id?{user,schoolId:r.school_id as string}:null;}
export async function POST(req:Request){const ctx=await context();if(!ctx)return NextResponse.json({error:"School Admin access required."},{status:403});const b=await req.json();const action=String(b.action||"");const a=createAdminClient();try{
 if(action==="create_subject"){const row={school_id:ctx.schoolId,name:String(b.name||"").trim(),code:String(b.code||"").trim()||null,description:String(b.description||"").trim()||null,status:"active"};if(!row.name)return NextResponse.json({error:"Subject name is required."},{status:400});const{data,error}=await a.from("subjects").insert(row).select("id").single();if(error)throw error;await a.from("audit_logs").insert({school_id:ctx.schoolId,user_id:ctx.user.id,action:"create",entity_type:"subject",entity_id:data.id,new_values:row});return NextResponse.json({ok:true});}
 if(action==="create_class"){const row={school_id:ctx.schoolId,academic_year_id:String(b.academic_year_id||""),class_level_id:String(b.class_level_id||"")||null,name:String(b.name||"").trim(),code:String(b.code||"").trim()||null,capacity:b.capacity?Number(b.capacity):null,status:"active"};if(!row.name||!row.academic_year_id)return NextResponse.json({error:"Class name and academic year are required."},{status:400});const{data,error}=await a.from("classes").insert(row).select("id").single();if(error)throw error;await a.from("audit_logs").insert({school_id:ctx.schoolId,user_id:ctx.user.id,action:"create",entity_type:"class",entity_id:data.id,new_values:row});return NextResponse.json({ok:true});}
 if(action==="toggle_subject"){const id=String(b.id||"");const{error}=await a.from("subjects").update({status:String(b.status||"inactive")}).eq("id",id).eq("school_id",ctx.schoolId);if(error)throw error;return NextResponse.json({ok:true});}
 if(action==="toggle_class"){const id=String(b.id||"");const{error}=await a.from("classes").update({status:String(b.status||"inactive")}).eq("id",id).eq("school_id",ctx.schoolId);if(error)throw error;return NextResponse.json({ok:true});}
 return NextResponse.json({error:"Unsupported action."},{status:400});
}catch(e:any){return NextResponse.json({error:e?.message||"Academic action failed."},{status:400});}}
