import {NextResponse} from "next/server";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";

async function context(){const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)return null;const{data:r}=await s.from("user_school_roles").select("role,school_id").eq("user_id",user.id).eq("is_active",true).eq("role","school_admin").maybeSingle();return r?.school_id?{user,schoolId:r.school_id as string}:null;}
const allowedStatus=new Set(["active","inactive"]);
export async function POST(req:Request){const ctx=await context();if(!ctx)return NextResponse.json({error:"School Admin access required."},{status:403});const b=await req.json();const action=String(b.action||"");const a=createAdminClient();try{
 if(action==="create_subject"){const row={school_id:ctx.schoolId,name:String(b.name||"").trim(),code:String(b.code||"").trim()||null,description:String(b.description||"").trim()||null,status:"active"};if(!row.name)return NextResponse.json({error:"Subject name is required."},{status:400});const{data,error}=await a.from("subjects").insert(row).select("id").single();if(error)throw error;await a.from("audit_logs").insert({school_id:ctx.schoolId,user_id:ctx.user.id,action:"create",entity_type:"subject",entity_id:data.id,new_values:row});return NextResponse.json({ok:true});}
 if(action==="create_class"){const yearId=String(b.academic_year_id||"");const levelId=String(b.class_level_id||"")||null;const row={school_id:ctx.schoolId,academic_year_id:yearId,class_level_id:levelId,name:String(b.name||"").trim(),code:String(b.code||"").trim()||null,capacity:b.capacity?Number(b.capacity):null,status:"active"};if(!row.name||!yearId)return NextResponse.json({error:"Class name and academic year are required."},{status:400});if(row.capacity!==null&&(!Number.isInteger(row.capacity)||row.capacity<1))return NextResponse.json({error:"Class capacity must be a positive whole number."},{status:400});const [year,level]=await Promise.all([a.from("academic_years").select("id").eq("id",yearId).eq("school_id",ctx.schoolId).maybeSingle(),levelId?a.from("class_levels").select("id").eq("id",levelId).eq("school_id",ctx.schoolId).maybeSingle():Promise.resolve({data:{id:null}} as any)]);if(!year.data||(levelId&&!level.data))return NextResponse.json({error:"Selected academic year or class level does not belong to this school."},{status:400});const{data,error}=await a.from("classes").insert(row).select("id").single();if(error)throw error;await a.from("audit_logs").insert({school_id:ctx.schoolId,user_id:ctx.user.id,action:"create",entity_type:"class",entity_id:data.id,new_values:row});return NextResponse.json({ok:true});}
 if(action==="toggle_subject"){const id=String(b.id||"");const status=String(b.status||"");if(!id||!allowedStatus.has(status))return NextResponse.json({error:"Valid subject and status are required."},{status:400});const{data:old}=await a.from("subjects").select("id,status").eq("id",id).eq("school_id",ctx.schoolId).maybeSingle();if(!old)return NextResponse.json({error:"Subject not found in this school."},{status:404});const{error}=await a.from("subjects").update({status}).eq("id",id).eq("school_id",ctx.schoolId);if(error)throw error;await a.from("audit_logs").insert({school_id:ctx.schoolId,user_id:ctx.user.id,action:"update",entity_type:"subject",entity_id:id,old_values:{status:old.status},new_values:{status}});return NextResponse.json({ok:true});}
 if(action==="toggle_class"){const id=String(b.id||"");const status=String(b.status||"");if(!id||!allowedStatus.has(status))return NextResponse.json({error:"Valid class and status are required."},{status:400});const{data:old}=await a.from("classes").select("id,status").eq("id",id).eq("school_id",ctx.schoolId).maybeSingle();if(!old)return NextResponse.json({error:"Class not found in this school."},{status:404});const{error}=await a.from("classes").update({status}).eq("id",id).eq("school_id",ctx.schoolId);if(error)throw error;await a.from("audit_logs").insert({school_id:ctx.schoolId,user_id:ctx.user.id,action:"update",entity_type:"class",entity_id:id,old_values:{status:old.status},new_values:{status}});return NextResponse.json({ok:true});}
 return NextResponse.json({error:"Unsupported action."},{status:400});
}catch(e:any){return NextResponse.json({error:e?.message||"Academic action failed."},{status:400});}}
